server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-productos
  r2dbc:
    # 1. Agregamos el prefijo r2dbc: antes del host de Neon y el parámetro de sslMode
    url: r2dbc:postgresql://${DB_HOST:ep-late-boat-atjvo9o0-pooler.c-9.us-east-1.aws.neon.tech}:5432/${DB_NAME:tienda}?sslMode=require
    # 2. Tu nuevo usuario dueño de la base de datos
    username: ${DB_USER:neondb_owner}
    # 3. Tu contraseña de Neon (limpia sin caracteres que confundan a la URL)
    password: ${DB_PASSWORD:npg_YyC1QWREbJ7O}