server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-productos
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:esdwbcoiisajpcjmvbud.supabase.co}:${DB_PORT:5432}/${DB_NAME:postgres}?sslMode=require
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:c4rl0sj03!0gUr1C4p}